### PR TITLE
Uniform generator for time series and histograms

### PR DESCRIPTION
**Pull request by tsengj10**
Generator code for TimeSeries and TimeHist objects, starting with just a uniform event rate over a given span.

One can create a TimeSeries or TimeHist using the NewTimeSeries or NewTimeHist generator.  Uniform then adds to the object.  One can then string together further generators to add to the objects.

We'll need to add some more utilities, like setting new start times and adding objects together, to make this fully functional.  This would be an alternative to creating a bunch of objects in the data['gen'], with a Combine at the end, which was getting a bit clumsy.

### CODE REVIEW

**Comment by tsengj10** [comment]
Need to pull this on top of master for it to work, because renderers/__init__.py refers to PickleOutput now

**Comment by mcolomermolla** [comment]
I see that for the pickle implementation (still looking at it), you have come back to old ".py" config files instead of csv:
snewpdag/data/test-pickle-in.py

Shouldn't it be also a csv?

**Comment by tsengj10** [comment]
Sometimes I find the old .py form easier for simple graphs.  But happy to make csv versions in a new PR!

**Comment by mcolomermolla** [comment]
Some comments:
- NewTimeHist: I would replace time_span by an end_time
- NewTimeSeries: why it one returns the start_time instead of all event times? I think I don't get the idea of this script
- TimeHist: I would not use default bins to zero to a non-zero value, as indeed it throws and error, and I think by default it should run for an arbitrary number of bins
- TimeSeries and TimeHist : I don't like the idea of having times as an array of (s,ns) times, it is just a factor 1000 and will be a lot more of data (and tuple structure) to handle
Question:
I don't reallysee how this connect to snewpdag/plugins/gen/TimeSeries.py after all

**Comment by mcolomermolla** [comment]
- I agree with that, I was just not seeing that "an amount of time after that" in the script that is defined/recorded
- You're right in theory for the experiment continuous data taking, there is no start and end for the event times (time series). However, for the practical case of a CCSN trigger, the experiment will define a start an an end that they will send to SNEWS as "the window the the supernova happens", and not hours or days of data. So I think we will get a start an end from experiments data first and last event they send.
- Yep, just a default value different from zero.
- (s,ns): I see, in any case yes, I think the amount of information lost is minimal (as in reality we won't achieve ns recision on the deltat or the T0). Also, experiments like IceCube and KM3NeT won't have a ns timing of events. 
- Yes, indeed, I see that the values.TimeSeries is defining a TimeSeries class, not really doing the "generator" part by randomising as in gen.TimeSeries

**Comment by tsengj10** [comment]
Good point about the duration - I'll add it to values.TimeSeries.  And possibly call it "duration" rather than "time_span".

Also will try to add the non-zero default nbins value - though I now recall why I didn't, which is that I had allowed the nbins parameter to override (i.e., shorten) the length of the data array in determining how many bins the histogram was to have.  Having a non-zero default value makes it impossible to specify "I want my histogram to have 100 bins, so truncate my array which happens to have 110 bins".  On the other hand, there are other ways to specify that outside of the arguments, but in any case it'll change the semantics of the nbins vs data.

Finally, I remembered that we automatically lose precision in the timestamp, so we may need to keep (s,ns) for anything which could be a full timestamp.  The reason is that the usual Unix-epoch timestamp uses nearly its full 32 bits - if I remember correctly, it turns over in the 2030's, possibly a bigger "Y2K" problem than the one in 1/1/2000.  A 64-bit float has 53 significant binary digits, so we're down to about 21 bits left for the fraction.  This only gets us down to microsecond granularity.

The detectors probably won't get down to ns timing granularity, but they do go below microseconds.  The main SNO+ trigger window, for instance, is 400ns, so if we cut the timestamp off at the microsecond level, it's possible to have two events with the same timestamp.  That could be a problem if we have to do some elementary data reduction within snewpdag.

Anyway, I'll see if I can reduce the number of ways one *must* use (s,ns), or indeed nanoseconds.  For instance, by adding methods which take floats instead of long ints.

That will be another PR, because I tangled up the git history a little and need to merge to straighten it out...

**Pull request merged**
